name: Build Linux

#on:
#  push:
#    branches: [ "main" ] 
#  pull_request:
#    branches: [ "main" ]
on:
  # Called to create release.
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:

jobs:
  linux_build:
    runs-on: ${{ matrix.platform.os }}-${{ matrix.platform.version }}
    strategy:
      matrix:
        platform:
          - os: ubuntu
            version: 22.04
            arch: x86_64
            build: release
    steps:
    - uses: actions/labeler@v4
      if: ${{ github.event_name == 'workflow_call' }}
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}

    - uses: actions/checkout@v3

    - name: Install MPFR library
      run: sudo apt-get install -y libmpfr-dev

    - name: Build default app
      run: make fpe
      working-directory: code

    - name: Build FP32, FP64, FP80 versions
      run: make hardware
      working-directory: code

    - name: List the binaries that where build in the previous steps
      run: ls -l ./bin

    - name: Basic test (dry run)
      run: ./FastPolyEval -help || true
      working-directory: bin

    - name: Archive binaries
      uses: actions/upload-artifact@v3
      with:
        name: FastPolyEval_${{ matrix.platform.arch }}_linux #${{ matrix.platform.os }}
        path: ./bin/FastPolyEval*

    - name: Cleanup
      run: make clean
      working-directory: code
